### PR TITLE
Update jekylltoghost.rb to work with Jekyll 4.0.0

### PR DESCRIPTION
**Pull request by tamersalama**
I was getting `undefined method `length' for nil:NilClass (NoMethodError) from `jekyll-4.0.0/lib/jekyll/static_file.rb:148:in `cleaned_relative_path'`.

extname (dir and name) as well as relative_path were empty (and they were part of Jekyll::StaticFile intializer. Added the setters to GhostPage initializer.

### CODE REVIEW

**Comment by mekomlusa** [comment]
LGTM. Thank you, Tamer!
